### PR TITLE
Add afford/cost geometric/arithmetic series functions.

### PR DESCRIPTION
**Pull request by Reinhardt-C**
I added them because I needed them for my game ;)

### CODE REVIEW

**Comment by Reinhardt-C** [comment]
The new functions are pretty much exact copies of the ones in Patashu's Break_Eternity.js. I needed them for my game and noticed you didn't have them so I decided to add them. They are static functions, starting on line 524. Hopefully someone else will find this useful.

**Comment by Reinhardt-C** [comment]
Also, I noticed you have a function called standarlize... is that a misspelling of standardize? I didn't change it because it is probably used in numerous other places in the code...

**Comment by Reinhardt-C** [comment]
This next part should fix #18 without compromising accuracy, you can still have 9 decimal points of accuracy, just changed code for .div slightly to fixt rogue floating point decimals.

**Comment by Reinhardt-C** [comment]
Codacy says that what I did will cause floating point errors ironically... I'll make that better... :(

**Comment by Reinhardt-C** [comment]
Codacy still says the same thing... I'll leave it and you can fix it if necessary, even though this is javascript and there is at least 8 bits for exponents while my number uses 5...

**Comment by Naruyoko** [comment]
Sorry for a late reply. This seems pretty awesome!

**Pull request merged**
